site_name: Payday2 BLT Documentation JP
site_author: PD2JP
repo_url: https://github.com/PD2JP/BLT-Docs
theme: readthedocs
pages:
- ['index.md', 'Home']
- ['globals/variables.md', 'グローバル', 'グローバル変数']
- ['globals/functions.md', 'グローバル', 'グローバル関数']
- ['globals/file.md', 'グローバル', 'ファイルIO']
- ['globals/console.md', 'グローバル', 'デバッグコンソール']
- ['mods/definition.md', 'Mod', 'Mod定義ファイル']
- ['mods/updates.md', 'Mod', '自動更新']
- ['mods/manager.md', 'Mod', 'Modマネージャー']
- ['lua/localization.md', 'Lua', 'ローカライゼーション']
- ['lua/hooks.md', 'Lua', 'Hooks']
- ['lua/delayed_calls.md', 'Lua', '遅延呼び出し']
- ['lua/notifications.md', 'Lua', '通知']
- ['lua/quick_menu.md', 'Lua', 'クイックメニュー']
- ['lua/json.md', 'Lua', 'Json']
- ['lua/utils.md', 'Lua', 'ユーティリティ']
- ['lua/menu/menu_helper.md', 'メニュー', 'メニューヘルパー']
- ['lua/menu/menu_helper_hooks.md', 'メニュー', 'メニューヘルパーHooks']
- ['lua/menu/json_menu.md', 'メニュー', 'Jsonメニュー']
- ['lua/network/network.md', 'ネットワーク', 'Luaネットワーク']
- ['lua/network/hooks.md', 'ネットワーク', 'Hooks']
- ['lua/network/extensions.md', 'ネットワーク', '拡張機能']
